[package]
name = "ttf-parser"
version = "0.4.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["ttf", "truetype", "opentype"]
categories = ["parser-implementations"]
license = "MIT/Apache-2.0"
description = "A high-level, safe, zero-allocation TrueType font parser."
repository = "https://github.com/RazrFalcon/ttf-parser"
documentation = "https://docs.rs/ttf-parser/"
readme = "README.md"
edition = "2018"
exclude = ["fonts/**"]

[features]
default = ["std", "logging"]
std = []
logging = ["log"]

[dependencies]
log = { version = "0.4.8", optional = true }

[dev-dependencies]
bencher = "0.1"
env_logger = { version = "0.7", default-features = false }
svgtypes = "0.5"
xmlwriter = "0.1"

[[bench]]
name = "outline"
harness = false

[[bench]]
name = "methods_perf"
harness = false

[[bench]]
name = "methods_perf_x1000"
harness = false

[package.metadata.docs.rs]
features = ["std"]
