[package]
name = "ttf-parser"
version = "0.4.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["ttf", "truetype", "opentype"]
categories = ["parser-implementations"]
license = "MIT/Apache-2.0"
description = "A high-level, safe, zero-allocation TrueType font parser."
repository = "https://github.com/RazrFalcon/ttf-parser"
documentation = "https://docs.rs/ttf-parser/"
readme = "README.md"
edition = "2018"
exclude = ["benches/**"]

[features]
default = ["std", "logging"]
std = []
logging = ["log"]

[dependencies]
log = { version = "0.4.8", optional = true }

[dev-dependencies]
env_logger = { version = "0.7", default-features = false }
pico-args = "0.3.1"
svgtypes = "0.5"
xmlwriter = "0.1"
