[package]
name = "ttf-parser-capi"
version = "0.1.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
license = "MIT"
edition = "2018"

[lib]
name = "ttfp"
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ttf-parser = { path = "../../" }
log = "0.4.8"
fern = "=0.5.8"
